export const uiStrings = {
  explore: "Explore",
  homepage_title: "The New World With Tourbay",
  homepage_subtitle:
    "No matter where in the world you want to go, we can help get you there and make your tour a stupendous memory.",
  exploreNews: "Explore News",
  tourbay: "Tourbay",
  addTour: "Add Tour",
  bookTour: "Book Tour",
  myTours: "My Tours",
  virtualization: "Virtualization",
  hondaAutos: "Honda Autos",

  whatsIncluded: "What's Included",
  destination: "Destination",
  departureLoc: "Departure Location",
  return: "Return",
  destinationValue: "Miami",
  departureAddress: "2000 Brush St, Detroit, MI 48226, United States",
  returnTime: "7:00 PM on Day 3",
  additionalInfo:
    "Basic first aid kit Basic first aid kit Basic first aid kit Basic first aid kit",

  bookNow: "Book Now",
  tourDesc: `The Pérez Art Museum Miami (PAMM) is a modern and contemporary art
        museum located in Miami, Florida. It is dedicated to collecting and
        exhibiting international art of the 20th and 21st centuries, with a
        particular focus on works from the Americas, Europe, and Africa.`,
  itinerary: "Itinerary Schedule",
  topDestinations: "Top Destinations",
  deleteConfirmation: "Delete Confirmation",
  deleteConfirmationMessage:
    "Are you sure you want to delete this booking? This action cannot be undone.",
  cancel: "Cancel",
  confirm: "Confirm",
  noToursMessage: "Sorry, We didn’t found any tour right now",
  chooseHere: "Choose Here",
  wantToDeleteBooking: "Are you sure you want to delete this booking?",
  deleteLimitText: ({ title }: { title: string }) =>
    `You can’t delete “${title}” because there are only 3 days remaining untill beginning of this tour. `,
  details: "Details",
  update: "Update",
  days: "days",
  viewDetails: "View Details",
  priceNotAvailable: "Price not available",
  confirmYourBooking: "Confirm Your Booking",
  enterYourName: "Enter your name",
  enterYourEmail: "Enter your email",
  enterYourPhone: "Enter your phone",
  numberOfAdults: "Number of Adults",
  numberOfChildren: "Number of Children",
  paymentMethod: "Payment Method",
  creditCard: "Credit Card",
  bankTransfer: "Bank Transfer",
  paypal: "PayPal",
  selectPaymentMethod: "Select payment method",
  popularSearch: "Popular Search",
  priceRange: "Price Range",
  chooseDate: "Choose Date",
  location: "Location",
  whereYouWantToGo: "Where you want to go?",
  searchPlaceholder: "Search by name or email",
};
