import type { HondaAuto } from "../../atoms/hondaAutosAtom";

export const hondaAutos: HondaAuto[] = [
  {
    id: 1,
    name: "Honda Civic",
    modelYear: 2022,
    price: 25000,
    engine: "1.5L Turbo",
    transmission: "CVT",
    fuelType: "Petrol",
    color: "White",
    chipText: "Hot Deal",
    imageSrc:
      "https://cdn.pixabay.com/photo/2019/08/04/23/28/honda-4384888_1280.jpg",
    description: "A sporty sedan blending style, comfort, and efficiency.",
    mileage: "15 km/l",
    fuelCapacity: "47 L",
  },
  {
    id: 2,
    name: "Honda Accord",
    modelYear: 2023,
    price: 32000,
    engine: "2.0L Turbo",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Black",
    imageSrc:
      "https://cdn.pixabay.com/photo/2017/04/21/02/20/jdm-2247450_1280.jpg",
    description: "Premium comfort meets powerful performance in this classic.",
    mileage: "14 km/l",
    fuelCapacity: "56 L",
  },
  {
    id: 3,
    name: "Honda CR-V",
    modelYear: 2022,
    price: 31000,
    engine: "1.5L Turbo",
    transmission: "CVT",
    fuelType: "Petrol",
    color: "Silver",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Versatile SUV with spacious interior and advanced safety.",
    mileage: "13 km/l",
    fuelCapacity: "57 L",
  },
  {
    id: 4,
    name: "Honda HR-V",
    modelYear: 2023,
    price: 27000,
    engine: "1.8L",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Red",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Compact crossover with bold design and flexible space.",
    mileage: "16 km/l",
    fuelCapacity: "40 L",
  },
  {
    id: 5,
    name: "Honda City",
    modelYear: 2021,
    price: 20000,
    engine: "1.5L",
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Blue",
    imageSrc:
      "https://cdn.pixabay.com/photo/2022/03/28/09/52/car-7097077_1280.png",
    description: "Urban favorite with sleek looks and smart features.",
    mileage: "17 km/l",
    fuelCapacity: "40 L",
  },
  {
    id: 6,
    name: "Honda Jazz",
    modelYear: 2022,
    price: 18000,
    engine: "1.2L",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Yellow",
    imageSrc:
      "https://cdn.pixabay.com/photo/2022/03/28/09/52/car-7097077_1280.png",
    description: "Compact hatchback with surprising space and agility.",
    mileage: "18 km/l",
    fuelCapacity: "40 L",
  },
  {
    id: 7,
    name: "Honda BR-V",
    modelYear: 2021,
    price: 22000,
    engine: "1.5L",
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Grey",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Family SUV with rugged looks and flexible seating.",
    mileage: "15 km/l",
    fuelCapacity: "42 L",
  },
  {
    id: 8,
    name: "Honda Odyssey",
    modelYear: 2023,
    price: 35000,
    engine: "3.5L V6",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "White",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Ultimate minivan for comfort, space, and family trips.",
    mileage: "11 km/l",
    fuelCapacity: "55 L",
  },
  {
    id: 9,
    name: "Honda Pilot",
    modelYear: 2022,
    price: 38000,
    engine: "3.5L V6",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Black",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Spacious SUV with power and advanced tech for adventures.",
    mileage: "10 km/l",
    fuelCapacity: "73 L",
  },
  {
    id: 10,
    name: "Honda Fit",
    modelYear: 2020,
    price: 17000,
    engine: "1.5L",
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Green",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Small car, big personality—perfect for city driving.",
    mileage: "19 km/l",
    fuelCapacity: "40 L",
  },
];

export const hondaAutosMoreData: HondaAuto[] = [
  {
    id: 11,
    name: "Honda Insight",
    modelYear: 2022,
    price: 26000,
    engine: "1.5L Hybrid",
    transmission: "CVT",
    fuelType: "Hybrid",
    color: "Silver",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Hybrid sedan that blends efficiency with elegance.",
    mileage: "22 km/l",
    fuelCapacity: "40 L",
  },
  {
    id: 12,
    name: "Honda Ridgeline",
    modelYear: 2023,
    price: 40000,
    engine: "3.5L V6",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Blue",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Rugged pickup with car-like comfort and utility.",
    mileage: "9 km/l",
    fuelCapacity: "73 L",
  },
  {
    id: 13,
    name: "Honda Passport",
    modelYear: 2022,
    price: 37000,
    engine: "3.5L V6",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Red",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Adventure-ready SUV with bold style and power.",
    mileage: "10 km/l",
    fuelCapacity: "73 L",
  },
  {
    id: 14,
    name: "Honda E",
    modelYear: 2021,
    price: 33000,
    engine: "Electric",
    transmission: "Automatic",
    fuelType: "Electric",
    color: "White",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Futuristic electric car with retro-inspired design.",
    mileage: "220 km/charge",
    fuelCapacity: "35.5 kWh",
  },
  {
    id: 15,
    name: "Honda S660",
    modelYear: 2020,
    price: 21000,
    engine: "0.66L Turbo",
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Yellow",
    imageSrc:
      "https://cdn.pixabay.com/photo/2018/10/23/20/42/engine-3768913_1280.jpg",
    description: "Fun, compact roadster for pure driving excitement.",
    mileage: "20 km/l",
    fuelCapacity: "25 L",
  },
  {
    id: 16,
    name: "Honda Freed",
    modelYear: 2022,
    price: 23000,
    engine: "1.5L Hybrid",
    transmission: "CVT",
    fuelType: "Hybrid",
    color: "Grey",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Smart minivan with hybrid efficiency and space.",
    mileage: "17 km/l",
    fuelCapacity: "36 L",
  },
  {
    id: 17,
    name: "Honda Stepwgn",
    modelYear: 2023,
    price: 29000,
    engine: "2.0L",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Silver",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Spacious van designed for family comfort and travel.",
    mileage: "15 km/l",
    fuelCapacity: "52 L",
  },
  {
    id: 18,
    name: "Honda Shuttle",
    modelYear: 2021,
    price: 21000,
    engine: "1.5L Hybrid",
    transmission: "CVT",
    fuelType: "Hybrid",
    color: "Blue",
    imageSrc:
      "https://cdn.pixabay.com/photo/2018/10/23/20/42/engine-3768913_1280.jpg",
    description: "Versatile wagon with hybrid power and ample cargo.",
    mileage: "23 km/l",
    fuelCapacity: "40 L",
  },
  {
    id: 19,
    name: "Honda N-Box",
    modelYear: 2022,
    price: 16000,
    engine: "0.66L",
    transmission: "CVT",
    fuelType: "Petrol",
    color: "Pink",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Ultra-compact kei car with maximum interior space.",
    mileage: "25 km/l",
    fuelCapacity: "27 L",
  },
  {
    id: 20,
    name: "Honda Clarity",
    modelYear: 2021,
    price: 34000,
    engine: "1.5L Plug-in Hybrid",
    transmission: "CVT",
    fuelType: "Hybrid",
    color: "White",
    imageSrc:
      "https://cdn.pixabay.com/photo/2021/03/10/17/40/car-6085109_1280.jpg",
    description: "Eco-friendly sedan with advanced hybrid technology.",
    mileage: "21 km/l",
    fuelCapacity: "26.5 L",
  },
];
